import { AgreementToProject } from "../types/Agreement_to_project.js";

// src/services/BORecordMap.ts
// BOName: Union type of all valid SuiteProjects business object names (used for type safety)
export type BOName =
  | "Customerpo"
  | "Invoice"
  | "BookingSummary"
  | "TimeEntry"
  | "Project"
  | "Slip"
  | "Timesheet"
  | "ApprovalLine"
  | "LeaveAccrualRule"
  | "Projectlocation"
  | "Customer"
  | "History"
  | "Costtype"
  | "ItemToUserLocation"
  | "Payrolltype"
  | "Product"
  | "Report"
  | "InvoiceLayout"
  | "AttributeDescription"
  | "Attachment"
  | "Currency"
  | "HierarchyNode"
  | "Preference"
  | "Jobcode"
  | "ForexInput"
  | "Filterset"
  | "Workspace"
  | "Workspaceuser"
  | "User"
  | "AccountingPeriod"
  | "Agreement_to_project"
  | "ActualCost"
  | "Agreement"
  | "ApprovalLine"
  | "ApprovalProcess"
  | "Attribute"
  | "AttributeDescription"
  | "AttributeSet"
  | "BillingSplit"
  | "Booking"
  | "BookingByDay"
  | "BookingRequest"
  | "BookingType"
  | "Budget"
  | "BudgetAllocation"
  | "Category"
  | "CategoryN"
  | "Ccrate"
  | "Company"
  | "Contact"
  | "CostCategory"
  | "CostCenter"
  | "CustomerLocation"
  | "CurrencyRate"
  | "Deal"
  | "DealContact"
  | "DealSchedule"
  | "DealToProject"
  | "Department"
  | "EntityTag"
  | "Envelope"
  | "Estimate"
  | "EstimateAdjustment"
  | "EstimateExpense"
  | "EstimateLabor"
  | "EstimateMarkup"
  | "EstimatePhase"
  | "Event"
  | "ExpensePolicy"
  | "ExpensePolicyItem"
  | "Filter"
  | "Fulfillment"
  | "Hierarchy"
  | "HistoryNotes"
  | "ImportExport"
  | "Issue"
  | "IssueCategory"
  | "IssueSeverity"
  | "IssueSource"
  | "IssueStage"
  | "IssueStatus"
  | "Item"
  | "JobCodeUsed"
  | "LeaveAccrualRuleToUser"
  | "LeaveAccrualTransaction"
  | "LoadedCost"
  | "Module"
  | "NewsFeed"
  | "NewsFeedMessage"
  | "Payment"
  | "PaymentTerms"
  | "PaymentType"
  | "PendingBooking"
  | "ProjectAssign"
  | "ProjectAssignmentProfile"
  | "ProjectBillingTransaction"
  | "ProjectBudgetGroup"
  | "ProjectBudgetRules"
  | "ProjectBudgetTransaction"
  | "ProjectGroup"
  | "ProjectPricing"
  | "ProjectStage"
  | "ProjectTask"
  | "ProjectTaskAssign"
  | "ProjectTaskEstimate"
  | "ProjectTask_Type"
  | "Proposal"
  | "ProposalBlock"
  | "Proxy"
  | "PurchaseItem"
  | "PurchaseOrder"
  | "PurchaseRequest"
  | "Purchaser"
  | "RateCardItem"
  | "Ratecard"
  | "Reimbursement"
  | "Repeat"
  | "Request_item"
  | "ResourceAttachment"
  | "ResourceProfile"
  | "ResourceProfileType"
  | "ResourceRequest"
  | "ResourceRequestQueue"
  | "ResourceSearch"
  | "RevenueContainer"
  | "RevenueProjection"
  | "RevenueRecognitionRule"
  | "RevenueRecognitionRuleAmount"
  | "RevenueRecognitionTransaction"
  | "RevenueStage"
  | "Role"
  | "ScheduleByDay"
  | "Scheduleexception"
  | "Schedulerequest"
  | "Schedulerequest_item"
  | "SlipProjection"
  | "SlipStage"
  | "SummaryView"
  | "TagGroup"
  | "TagGroupAttribute"
  | "TargetUtilization"
  | "Task"
  | "TaskTimecard"
  | "TaskAdjustment"
  | "TaxLocation"
  | "TaxRate"
  | "Term"
  | "Ticket"
  | "TimeType"
  | "Timecard"
  | "Todo"
  | "Uprate"
  | "UserWorkSchedule"
  | "Vendor"
  | "ViewFilter"
  | "ViewFilterRule"
  | "UserLocation"
  | "WorkScheduleWorkHour"
  | "WorkspaceLink";

// Generic Wrapper type to dynamically determine the wrapper for a given BOName
export type Wrapper<T extends BOName> = {
  [K in T]: any; // Replace 'any' with the actual type if needed
};

// Override mapping for Agreement_to_project
import { BookingSummary } from "../types/BookingSummary";
import { TimeEntry } from "../types/TimeEntry";

export interface ExplicitBORecordMap {
  Agreement_to_project: AgreementToProject;
  BookingSummary: BookingSummary;
  TimeEntry: TimeEntry;
}

export type BORecordMap = ExplicitBORecordMap & {
  [K in Exclude<BOName, "Agreement_to_project">]: Wrapper<K>[K];
};

// WrapperWithStatus: Used for parsing a single API response item with status (for error handling)
export type WrapperWithStatus<K extends BOName> = {
  [P in K]: BORecordMap[K];
} & { status?: string };