// src/types/LeaveAccrualTransaction.ts

import { DateContainer } from "./Timesheet";

export interface LeaveAccrualTransaction {
  id: string;                          // [Read-only]
  leave_accrual_ruleid: string;        // [Required]
  userid: string;                      // [Required]
  date: DateContainer;                        // YYYY-MM-DD [Required]
  type: 'D' | 'A';                     // D=draw down, A=accrual
  amount: number;                      // positive for accrual, negative for draw down
  from_run?: string;                   // flag if generated by run
  taskid?: string;                     // if draw down against a timesheet entry
  notes?: string;
  created: DateContainer;                     // [Read-only]
  updated: DateContainer;                     // [Read-only]
}

export interface LeaveAccrualTransactionWrapper {
  leave_accrual_transaction: LeaveAccrualTransaction;
}
