// src/types/SlipProjection.ts
import { DateContainer } from "./Timesheet";
/**
 * A charge projection generated by a billing-projection run.
 * Read-only (supports only Read).
 */
export interface SlipProjection {
  id: string;                          // [Read-only] Unique ID :contentReference[oaicite:0]{index=0}:contentReference[oaicite:1]{index=1}
  acct_date?: string;                  // Accounting-period date :contentReference[oaicite:2]{index=2}:contentReference[oaicite:3]{index=3}
  agreementid?: string;                // Agreement ID :contentReference[oaicite:4]{index=4}:contentReference[oaicite:5]{index=5}
  billing_contactid?: string;          // Billing contact ID :contentReference[oaicite:6]{index=6}:contentReference[oaicite:7]{index=7}
  booking_typeid?: string;             // Booking type ID :contentReference[oaicite:8]{index=8}:contentReference[oaicite:9]{index=9}
  categoryid?: string;                 // Category ID :contentReference[oaicite:10]{index=10}:contentReference[oaicite:11]{index=11}
  city?: string;                       // Slip city/location :contentReference[oaicite:12]{index=12}:contentReference[oaicite:13]{index=13}
  cost?: number;                       // Cost per unit :contentReference[oaicite:14]{index=14}:contentReference[oaicite:15]{index=15}
  cost_centerid?: string;              // Cost-center ID :contentReference[oaicite:16]{index=16}:contentReference[oaicite:17]{index=17}
  created: string;                     // [Read-only] Created timestamp :contentReference[oaicite:18]{index=18}:contentReference[oaicite:19]{index=19}
  currency?: string;                   // Currency code :contentReference[oaicite:20]{index=20}:contentReference[oaicite:21]{index=21}
  customerid?: string;                 // Customer ID :contentReference[oaicite:22]{index=22}:contentReference[oaicite:23]{index=23}
  customerpoid?: string;               // Customer PO ID :contentReference[oaicite:24]{index=24}:contentReference[oaicite:25]{index=25}
  date: DateContainer;                        // Slip date :contentReference[oaicite:26]{index=26}:contentReference[oaicite:27]{index=27}
  decimal_hours?: number;              // Decimal hours (T-slip) :contentReference[oaicite:28]{index=28}:contentReference[oaicite:29]{index=29}
  description?: string;                // Description :contentReference[oaicite:30]{index=30}:contentReference[oaicite:31]{index=31}
  hour?: number;                       // Hours (T-slip) :contentReference[oaicite:32]{index=32}:contentReference[oaicite:33]{index=33}
  minute?: number;                     // Minutes (T-slip) :contentReference[oaicite:34]{index=34}:contentReference[oaicite:35]{index=35}
  quantity?: number;                   // Quantity (E/O/P) :contentReference[oaicite:36]{index=36}:contentReference[oaicite:37]{index=37}
  rate?: number;                       // Rate for T-slip :contentReference[oaicite:38]{index=38}:contentReference[oaicite:39]{index=39}
  shipping_contactid?: string;         // Shipping contact ID :contentReference[oaicite:40]{index=40}:contentReference[oaicite:41]{index=41}
  skip_recognition?: '1' | '0';        // Skip recognition flag :contentReference[oaicite:42]{index=42}:contentReference[oaicite:43]{index=43}
  slip_stageid?: string;               // Slip-stage ID :contentReference[oaicite:44]{index=44}:contentReference[oaicite:45]{index=45}
  sold_to_contactid?: string;          // Sold-to contact ID :contentReference[oaicite:46]{index=46}:contentReference[oaicite:47]{index=47}
  timer_start?: string;                // Timer-start timestamp :contentReference[oaicite:48]{index=48}:contentReference[oaicite:49]{index=49}
  timetypeid?: string;                 // Time-type ID :contentReference[oaicite:50]{index=50}:contentReference[oaicite:51]{index=51}
  total?: number;                      // Total value :contentReference[oaicite:52]{index=52}:contentReference[oaicite:53]{index=53}
  total_tax?: number;                  // Total tax paid :contentReference[oaicite:54]{index=54}:contentReference[oaicite:55]{index=55}
  total_with_tax?: number;             // Total including tax :contentReference[oaicite:56]{index=56}:contentReference[oaicite:57]{index=57}
  transactionid?: string;              // Internal transaction ID :contentReference[oaicite:58]{index=58}:contentReference[oaicite:59]{index=59}
  type: 'T' | 'E' | 'F' | 'O' | 'M' | 'P'; // Slip type :contentReference[oaicite:60]{index=60}:contentReference[oaicite:61]{index=61}
  unitm?: string;                      // Unit of measure :contentReference[oaicite:62]{index=62}:contentReference[oaicite:63]{index=63}
  updated: DateContainer                     // [Read-only] Updated timestamp :contentReference[oaicite:64]{index=64}:contentReference[oaicite:65]{index=65}
}

export interface SlipProjectionWrapper {
  SlipProjection: SlipProjection;
}
